import { autocompletion, Completion } from '@codemirror/autocomplete';

const cppKeywords: Completion[] = [
  { label: 'auto', type: 'keyword' },
  { label: 'break', type: 'keyword' },
  { label: 'case', type: 'keyword' },
  { label: 'catch', type: 'keyword' },
  { label: 'class', type: 'keyword' },
  { label: 'const', type: 'keyword' },
  { label: 'constexpr', type: 'keyword' },
  { label: 'continue', type: 'keyword' },
  { label: 'default', type: 'keyword' },
  { label: 'delete', type: 'keyword' },
  { label: 'do', type: 'keyword' },
  { label: 'double', type: 'keyword' },
  { label: 'else', type: 'keyword' },
  { label: 'enum', type: 'keyword' },
  { label: 'explicit', type: 'keyword' },
  { label: 'extern', type: 'keyword' },
  { label: 'false', type: 'keyword' },
  { label: 'float', type: 'keyword' },
  { label: 'for', type: 'keyword' },
  { label: 'friend', type: 'keyword' },
  { label: 'goto', type: 'keyword' },
  { label: 'if', type: 'keyword' },
  { label: 'inline', type: 'keyword' },
  { label: 'int', type: 'keyword' },
  { label: 'long', type: 'keyword' },
  { label: 'namespace', type: 'keyword' },
  { label: 'new', type: 'keyword' },
  { label: 'noexcept', type: 'keyword' },
  { label: 'nullptr', type: 'keyword' },
  { label: 'operator', type: 'keyword' },
  { label: 'private', type: 'keyword' },
  { label: 'protected', type: 'keyword' },
  { label: 'public', type: 'keyword' },
  { label: 'return', type: 'keyword' },
  { label: 'short', type: 'keyword' },
  { label: 'signed', type: 'keyword' },
  { label: 'sizeof', type: 'keyword' },
  { label: 'static', type: 'keyword' },
  { label: 'struct', type: 'keyword' },
  { label: 'switch', type: 'keyword' },
  { label: 'template', type: 'keyword' },
  { label: 'this', type: 'keyword' },
  { label: 'throw', type: 'keyword' },
  { label: 'true', type: 'keyword' },
  { label: 'try', type: 'keyword' },
  { label: 'typedef', type: 'keyword' },
  { label: 'typename', type: 'keyword' },
  { label: 'union', type: 'keyword' },
  { label: 'unsigned', type: 'keyword' },
  { label: 'using', type: 'keyword' },
  { label: 'virtual', type: 'keyword' },
  { label: 'void', type: 'keyword' },
  { label: 'volatile', type: 'keyword' },
  { label: 'while', type: 'keyword' },
  { label: 'bool', type: 'keyword' },
  { label: 'char', type: 'keyword' },
  { label: 'char16_t', type: 'keyword' },
  { label: 'char32_t', type: 'keyword' },
  { label: 'wchar_t', type: 'keyword' },
  { label: 'size_t', type: 'keyword' },
  { label: 'long long', type: 'keyword' },
  { label: 'typedef', type: 'keyword' },
];

const stlContainers: Completion[] = [
  { label: 'string', type: 'type', detail: 'std::string' },
  { label: 'vector', type: 'type', detail: 'std::vector' },
  { label: 'pair', type: 'type', detail: 'std::pair' },
  { label: 'map', type: 'type', detail: 'std::map' },
  { label: 'set', type: 'type', detail: 'std::set' },
  { label: 'multimap', type: 'type', detail: 'std::multimap' },
  { label: 'multiset', type: 'type', detail: 'std::multiset' },
  { label: 'unordered_map', type: 'type', detail: 'std::unordered_map' },
  { label: 'unordered_set', type: 'type', detail: 'std::unordered_set' },
  { label: 'queue', type: 'type', detail: 'std::queue' },
  { label: 'stack', type: 'type', detail: 'std::stack' },
  { label: 'deque', type: 'type', detail: 'std::deque' },
  { label: 'priority_queue', type: 'type', detail: 'std::priority_queue' },
  { label: 'bitset', type: 'type', detail: 'std::bitset' },
  { label: 'array', type: 'type', detail: 'std::array' },
  { label: 'tuple', type: 'type', detail: 'std::tuple' },
  { label: 'list', type: 'type', detail: 'std::list' },
  { label: 'forward_list', type: 'type', detail: 'std::forward_list' },
];

const stlFunctions: Completion[] = [
  { label: 'sort', type: 'function', detail: 'sort(begin, end)' },
  { label: 'stable_sort', type: 'function', detail: 'stable_sort(begin, end)' },
  { label: 'reverse', type: 'function', detail: 'reverse(begin, end)' },
  { label: 'unique', type: 'function', detail: 'unique(begin, end)' },
  { label: 'lower_bound', type: 'function', detail: 'lower_bound(begin, end, val)' },
  { label: 'upper_bound', type: 'function', detail: 'upper_bound(begin, end, val)' },
  { label: 'binary_search', type: 'function', detail: 'binary_search(begin, end, val)' },
  { label: 'min_element', type: 'function', detail: 'min_element(begin, end)' },
  { label: 'max_element', type: 'function', detail: 'max_element(begin, end)' },
  { label: 'count', type: 'function', detail: 'count(begin, end, val)' },
  { label: 'find', type: 'function', detail: 'find(begin, end, val)' },
  { label: 'fill', type: 'function', detail: 'fill(begin, end, val)' },
  { label: 'copy', type: 'function', detail: 'copy(begin, end, dest)' },
  { label: 'swap', type: 'function', detail: 'swap(a, b)' },
  { label: 'next_permutation', type: 'function', detail: 'next_permutation(begin, end)' },
  { label: 'accumulate', type: 'function', detail: 'accumulate(begin, end, init)' },
  { label: 'abs', type: 'function', detail: 'abs(x)' },
  { label: 'sqrt', type: 'function', detail: 'sqrt(x)' },
  { label: 'pow', type: 'function', detail: 'pow(base, exp)' },
  { label: 'log', type: 'function', detail: 'log(x)' },
  { label: 'ceil', type: 'function', detail: 'ceil(x)' },
  { label: 'floor', type: 'function', detail: 'floor(x)' },
  { label: 'max', type: 'function', detail: 'max(a, b)' },
  { label: 'min', type: 'function', detail: 'min(a, b)' },
  { label: 'gcd', type: 'function', detail: 'gcd(a, b) C++17' },
  { label: 'lcm', type: 'function', detail: 'lcm(a, b) C++17' },
  { label: 'push_back', type: 'function', detail: 'push_back(val)' },
  { label: 'pop_back', type: 'function', detail: 'pop_back()' },
  { label: 'push_front', type: 'function', detail: 'push_front(val)' },
  { label: 'pop_front', type: 'function', detail: 'pop_front()' },
  { label: 'insert', type: 'function', detail: 'insert(pos, val)' },
  { label: 'erase', type: 'function', detail: 'erase(pos)' },
  { label: 'clear', type: 'function', detail: 'clear()' },
  { label: 'size', type: 'function', detail: 'size()' },
  { label: 'empty', type: 'function', detail: 'empty()' },
  { label: 'begin', type: 'function', detail: 'begin()' },
  { label: 'end', type: 'function', detail: 'end()' },
  { label: 'front', type: 'function', detail: 'front()' },
  { label: 'back', type: 'function', detail: 'back()' },
  { label: 'resize', type: 'function', detail: 'resize(n)' },
  { label: 'substr', type: 'function', detail: 'substr(pos, len)' },
  { label: 'find_first_of', type: 'function', detail: 'find_first_of(str)' },
  { label: 'to_string', type: 'function', detail: 'to_string(num)' },
  { label: 'stoi', type: 'function', detail: 'stoi(str)' },
  { label: 'stoll', type: 'function', detail: 'stoll(str)' },
];

const iostreamItems: Completion[] = [
  { label: 'cin', type: 'variable', detail: 'std::cin' },
  { label: 'cout', type: 'variable', detail: 'std::cout' },
  { label: 'cerr', type: 'variable', detail: 'std::cerr' },
  { label: 'endl', type: 'variable', detail: 'std::endl' },
  { label: 'fixed', type: 'keyword', detail: 'fixed output format' },
  { label: 'scientific', type: 'keyword', detail: 'scientific output format' },
  { label: 'setprecision', type: 'function', detail: 'setprecision(n) <iomanip>' },
  { label: 'setw', type: 'function', detail: 'setw(n) <iomanip>' },
  { label: 'setfill', type: 'function', detail: 'setfill(c) <iomanip>' },
  { label: 'setbase', type: 'function', detail: 'setbase(n) <iomanip>' },
  { label: 'hex', type: 'keyword', detail: 'hex output format' },
  { label: 'oct', type: 'keyword', detail: 'oct output format' },
  { label: 'dec', type: 'keyword', detail: 'dec output format' },
  { label: 'left', type: 'keyword', detail: 'left align' },
  { label: 'right', type: 'keyword', detail: 'right align' },
  { label: 'getline', type: 'function', detail: 'getline(cin, str)' },
  { label: 'stringstream', type: 'type', detail: 'std::stringstream' },
  { label: 'istringstream', type: 'type', detail: 'std::istringstream' },
  { label: 'ostringstream', type: 'type', detail: 'std::ostringstream' },
];

const gccBuiltins: Completion[] = [
  { label: '__builtin_popcount', type: 'function', detail: 'popcount(x)' },
  { label: '__builtin_popcountll', type: 'function', detail: 'popcount(long long)' },
  { label: '__builtin_clz', type: 'function', detail: 'count leading zeros' },
  { label: '__builtin_clzll', type: 'function', detail: 'count leading zeros (ll)' },
  { label: '__builtin_ctz', type: 'function', detail: 'count trailing zeros' },
  { label: '__builtin_ctzll', type: 'function', detail: 'count trailing zeros (ll)' },
  { label: '__builtin_ffs', type: 'function', detail: 'find first set bit' },
  { label: '__builtin_parity', type: 'function', detail: 'parity of bits' },
];

const moreStl: Completion[] = [
  { label: 'nth_element', type: 'function', detail: 'nth_element(begin, nth, end)' },
  { label: 'partial_sort', type: 'function', detail: 'partial_sort(begin, middle, end)' },
  { label: 'make_heap', type: 'function', detail: 'make_heap(begin, end)' },
  { label: 'push_heap', type: 'function', detail: 'push_heap(begin, end)' },
  { label: 'pop_heap', type: 'function', detail: 'pop_heap(begin, end)' },
  { label: 'merge', type: 'function', detail: 'merge(begin1, end1, begin2, end2, dest)' },
  { label: 'includes', type: 'function', detail: 'includes(begin1, end1, begin2, end2)' },
  { label: 'set_union', type: 'function', detail: 'set_union(...)' },
  { label: 'set_intersection', type: 'function', detail: 'set_intersection(...)' },
  { label: 'set_difference', type: 'function', detail: 'set_difference(...)' },
  { label: 'minmax', type: 'function', detail: 'minmax(a, b)' },
  { label: 'clamp', type: 'function', detail: 'clamp(val, lo, hi) C++17' },
  { label: 'gcd', type: 'function', detail: 'gcd(a, b) C++17' },
  { label: 'lcm', type: 'function', detail: 'lcm(a, b) C++17' },
  { label: 'midpoint', type: 'function', detail: 'midpoint(a, b) C++20' },
  { label: 'lerp', type: 'function', detail: 'lerp(a, b, t) C++20' },
  { label: 'ssize', type: 'function', detail: 'ssize(container) C++20' },
  { label: 'contains', type: 'function', detail: 'container.contains(key) C++20' },
  { label: 'count_if', type: 'function', detail: 'count_if(begin, end, pred)' },
  { label: 'find_if', type: 'function', detail: 'find_if(begin, end, pred)' },
  { label: 'remove_if', type: 'function', detail: 'remove_if(begin, end, pred)' },
  { label: 'replace', type: 'function', detail: 'replace(begin, end, old, new)' },
  { label: 'transform', type: 'function', detail: 'transform(begin, end, dest, op)' },
  { label: 'for_each', type: 'function', detail: 'for_each(begin, end, fn)' },
  { label: 'all_of', type: 'function', detail: 'all_of(begin, end, pred)' },
  { label: 'any_of', type: 'function', detail: 'any_of(begin, end, pred)' },
  { label: 'none_of', type: 'function', detail: 'none_of(begin, end, pred)' },
  { label: 'is_sorted', type: 'function', detail: 'is_sorted(begin, end)' },
  { label: 'iota', type: 'function', detail: 'iota(begin, end, value)' },
];

const allCompletions = [...cppKeywords, ...stlContainers, ...stlFunctions, ...iostreamItems, ...gccBuiltins, ...moreStl];

export function cppCompletion() {
  return autocompletion({
    override: [
      (context) => {
        const word = context.matchBefore(/\w*/);
        if (!word || (word.from === word.to && !context.explicit)) return null;
        return {
          from: word.from,
          options: allCompletions,
        };
      },
    ],
  });
}
